spring:
  application:
    name: crawlify-node
  datasource:
    url: jdbc:mysql://localhost:3306/crawlify?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useAffectedRows=true&allowMultiQueries=true&multiStatementAllow=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 30
      pool-name: crawlify


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.crawlify.entity